# Load RUCKUS environment and library
source -quiet $::env(RUCKUS_DIR)/vivado_proc.tcl

# Global
loadSource      -path "$::DIR_PATH/hdl/design/global_pkg.vhd"
loadSource      -path "$::DIR_PATH/hdl/design/global_pkg.sv"
loadSource      -path "$::DIR_PATH/hdl/design/track_gen_bram/track_gen_bram.vhd"
loadIpCore      -dir "$::DIR_PATH/hdl/ip/xilinx/clock/clk_wiz_160_250"
loadIpCore      -dir "$::DIR_PATH/hdl/ip/xilinx/clock/clk_wiz_320_390"
loadIpCore      -dir "$::DIR_PATH/hdl/ip/xilinx/clock/clk_320to213"
loadIpCore      -dir "$::DIR_PATH/hdl/ip/xilinx/clock/clk_320to227"
loadIpCore      -dir "$::DIR_PATH/hdl/ip/xilinx/clock/clk_320to300"
loadIpCore      -dir "$::DIR_PATH/hdl/ip/xilinx/clock/clk_360to240"
loadIpCore      -dir "$::DIR_PATH/hdl/ip/xilinx/clock/clk_360to259"
loadIpCore      -dir "$::DIR_PATH/hdl/ip/xilinx/clock/clk_360to330"
loadIpCore      -dir "$::DIR_PATH/hdl/ip/xilinx/clock/clk_360to390"
# Test infra
loadIpCore      -dir "$::DIR_PATH/hdl/ip/xilinx/ram/blk_mem_gen_1728bx7040"
loadIpCore      -dir "$::DIR_PATH/hdl/ip/xilinx/ila/ila_algo"
loadIpCore      -dir "$::DIR_PATH/hdl/ip/xilinx/ila/ila_hist"
loadIpCore      -dir "$::DIR_PATH/hdl/ip/xilinx/ila/ila_track_conv"
loadIpCore      -dir "$::DIR_PATH/hdl/ip/xilinx/vio/vio_algo"
loadIpCore      -dir "$::DIR_PATH/hdl/ip/xilinx/ila/ila_18in_3out"
# Algo
loadSource      -dir "$::DIR_PATH/hdl/design/track_selection/"
loadSource      -dir "$::DIR_PATH/hdl/design/met/"
	# Select single vtx HLS files to avoid duplicates
loadSource      -dir "$::DIR_PATH/hdl/design/vertex_hls/"
loadConstraints -path "$::DIR_PATH/hdl/design/vertex_hls/vertex_histogram.xdc"
loadSource      -dir "$::DIR_PATH/hdl/tb/vertex_hls/"
#loadSource      -path "$::DIR_PATH/hdl/design/vertex_hls/vtx_find_only/fifo_w1_d2_A.vhd" # duplicate (met)
loadSource      -path "$::DIR_PATH/hdl/design/vertex_hls/vtx_find_only/fifo_w7_d2_A.vhd"
loadSource      -path "$::DIR_PATH/hdl/design/vertex_hls/vtx_find_only/fifo_w9_d2_A.vhd"
loadSource      -path "$::DIR_PATH/hdl/design/vertex_hls/vtx_find_only/fifo_w10_d2_A.vhd"
loadSource      -path "$::DIR_PATH/hdl/design/vertex_hls/vtx_find_only/fifo_w11_d2_A.vhd"
loadSource      -path "$::DIR_PATH/hdl/design/vertex_hls/vtx_find_only/initialize_array_of_objects_1u_VtxObj_76.vhd"
loadSource      -path "$::DIR_PATH/hdl/design/vertex_hls/vtx_find_only/pack_out.vhd"
loadSource      -path "$::DIR_PATH/hdl/design/vertex_hls/vtx_find_only/start_for_pack_out_U0.vhd"
loadSource      -path "$::DIR_PATH/hdl/design/vertex_hls/vtx_find_only/start_for_tkobjalgo_find_vtx_U0.vhd"
loadSource      -path "$::DIR_PATH/hdl/design/vertex_hls/vtx_find_only/tkobjalgo_compute_sums.vhd"
loadSource      -path "$::DIR_PATH/hdl/design/vertex_hls/vtx_find_only/tkobjalgo_find_vtx_inversion_table1.vhd"
loadSource      -path "$::DIR_PATH/hdl/design/vertex_hls/vtx_find_only/tkobjalgo_find_vtx.vhd"
loadSource      -path "$::DIR_PATH/hdl/design/vertex_hls/vtx_find_only/tkobjalgo_mul_mul_11ns_14ns_25_3_1.vhd"
loadSource      -path "$::DIR_PATH/hdl/design/vertex_hls/vtx_find_only/tkobjalgo_mux_1287_9_1_1.vhd"
loadSource      -path "$::DIR_PATH/hdl/design/vertex_hls/vtx_find_only/tkobjalgo.vhd"
	# Select single vtx HLS files to avoid duplicates
loadSource      -dir "$::DIR_PATH/hdl/design/jet_finding/"
loadIpCore      -dir "$::DIR_PATH/hdl/ip/xilinx/ila/ila_jet_finding/"
#loadSource      -dir "$::DIR_PATH/hdl/design/Jet_Finding_TS/"
loadSource      -path "$::DIR_PATH/hdl/design/Jet_Finding_TS/jet_finding_tb_TS.v"
loadSource      -path "$::DIR_PATH/hdl/design/Jet_Finding_TS/jet_finding_tb.v"
loadSource      -path "$::DIR_PATH/hdl/design/Jet_Finding_TS/jet_finding_top_TS.v"
# Track conversion
loadSource      -dir "$::DIR_PATH/hdl/design/p_T/"
loadSource      -path "$::DIR_PATH/hdl/tb/p_T/tb_p_T.vhd"
loadSource      -dir "$::DIR_PATH/hdl/design/eta/"
loadSource      -path "$::DIR_PATH/hdl/tb/eta/tb_eta.vhd"
loadSource      -dir "$::DIR_PATH/hdl/design/track_conv/"
loadSource      -path "$::DIR_PATH/hdl/tb/track_conv/tb_track_conv.vhd"
# Conversion
loadSource      -dir "$::DIR_PATH/hdl/design/conv/"
loadSource      -dir "$::DIR_PATH/hdl/tb/conv/"
loadConstraints -path "$::DIR_PATH/hdl/design/conv/conv64bto96bFIFO.xdc"
loadIpCore      -dir "$::DIR_PATH/hdl/ip/xilinx/ram/fifo_dist_118bx16"
loadConstraints -path "$::DIR_PATH/hdl/design/conv/conv96bto64bFIFO.xdc"
loadIpCore      -dir "$::DIR_PATH/hdl/ip/xilinx/ram/fifo_dist_96bx117"
loadIpCore      -dir "$::DIR_PATH/hdl/ip/xilinx/ram/fifo_builtin_96bx512"
