-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity generic_sincos is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    in_V : IN STD_LOGIC_VECTOR (17 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of generic_sincos is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv18_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_2A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101010";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv21_C90FD : STD_LOGIC_VECTOR (20 downto 0) := "011001001000011111101";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv20_0 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv43_145F306 : STD_LOGIC_VECTOR (42 downto 0) := "0000000000000000001010001011111001100000110";
    constant ap_const_lv21_6DE05 : STD_LOGIC_VECTOR (20 downto 0) := "001101101111000000101";

    signal sign0_V_fu_79_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sign0_V_reg_366 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter12 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter13 : BOOLEAN;
    signal ap_block_state15_pp0_stage0_iter14 : BOOLEAN;
    signal ap_block_state16_pp0_stage0_iter15 : BOOLEAN;
    signal ap_block_state17_pp0_stage0_iter16 : BOOLEAN;
    signal ap_block_state18_pp0_stage0_iter17 : BOOLEAN;
    signal ap_block_state19_pp0_stage0_iter18 : BOOLEAN;
    signal ap_block_state20_pp0_stage0_iter19 : BOOLEAN;
    signal ap_block_state21_pp0_stage0_iter20 : BOOLEAN;
    signal ap_block_state22_pp0_stage0_iter21 : BOOLEAN;
    signal ap_block_state23_pp0_stage0_iter22 : BOOLEAN;
    signal ap_block_state24_pp0_stage0_iter23 : BOOLEAN;
    signal ap_block_state25_pp0_stage0_iter24 : BOOLEAN;
    signal ap_block_state26_pp0_stage0_iter25 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal sign0_V_reg_366_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sign0_V_reg_366_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sign0_V_reg_366_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sign0_V_reg_366_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sign0_V_reg_366_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sign0_V_reg_366_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sign0_V_reg_366_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sign0_V_reg_366_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sign0_V_reg_366_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sign0_V_reg_366_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sign0_V_reg_366_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sign0_V_reg_366_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sign0_V_reg_366_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sign0_V_reg_366_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sign0_V_reg_366_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sign0_V_reg_366_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sign0_V_reg_366_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sign0_V_reg_366_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sign0_V_reg_366_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sign0_V_reg_366_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sign0_V_reg_366_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sign0_V_reg_366_pp0_iter22_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sign0_V_reg_366_pp0_iter23_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sign0_V_reg_366_pp0_iter24_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_s_fu_91_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_Val2_s_reg_371 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln728_fu_99_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln728_reg_376 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln728_reg_376_pp0_iter1_reg : STD_LOGIC_VECTOR (14 downto 0);
    signal r_V_8_fu_352_p2 : STD_LOGIC_VECTOR (42 downto 0);
    signal r_V_8_reg_381 : STD_LOGIC_VECTOR (42 downto 0);
    signal k_V_reg_387 : STD_LOGIC_VECTOR (1 downto 0);
    signal k_V_reg_387_pp0_iter3_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal k_V_reg_387_pp0_iter4_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal k_V_reg_387_pp0_iter5_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal k_V_reg_387_pp0_iter6_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal k_V_reg_387_pp0_iter7_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal k_V_reg_387_pp0_iter8_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal k_V_reg_387_pp0_iter9_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal k_V_reg_387_pp0_iter10_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal k_V_reg_387_pp0_iter11_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal k_V_reg_387_pp0_iter12_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal k_V_reg_387_pp0_iter13_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal k_V_reg_387_pp0_iter14_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal k_V_reg_387_pp0_iter15_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal k_V_reg_387_pp0_iter16_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal k_V_reg_387_pp0_iter17_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal k_V_reg_387_pp0_iter18_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal k_V_reg_387_pp0_iter19_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal k_V_reg_387_pp0_iter20_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal k_V_reg_387_pp0_iter21_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal k_V_reg_387_pp0_iter22_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal k_V_reg_387_pp0_iter23_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_358_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal ret_V_reg_395 : STD_LOGIC_VECTOR (20 downto 0);
    signal icmp_ln879_fu_144_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_reg_401 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_reg_401_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_reg_401_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_reg_401_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_reg_401_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_reg_401_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_reg_401_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_reg_401_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_reg_401_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_reg_401_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_reg_401_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_reg_401_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_reg_401_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_reg_401_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_reg_401_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_reg_401_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_reg_401_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_reg_401_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_reg_401_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_reg_401_pp0_iter22_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_reg_401_pp0_iter23_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal z_V_fu_193_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal z_V_reg_406 : STD_LOGIC_VECTOR (19 downto 0);
    signal empty_fu_205_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal empty_reg_411 : STD_LOGIC_VECTOR (19 downto 0);
    signal trunc_ln266_fu_213_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal trunc_ln266_reg_416 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_s_reg_421 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_28_reg_427 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_25_fu_291_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_25_reg_433 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln879_4_fu_322_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln879_4_reg_439 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_cordic_circ_apfixed_fu_70_ap_return_0 : STD_LOGIC_VECTOR (20 downto 0);
    signal grp_cordic_circ_apfixed_fu_70_ap_return_1 : STD_LOGIC_VECTOR (20 downto 0);
    signal grp_cordic_circ_apfixed_fu_70_ap_ce : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call24 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call24 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call24 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call24 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call24 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5_ignore_call24 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6_ignore_call24 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7_ignore_call24 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8_ignore_call24 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9_ignore_call24 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10_ignore_call24 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11_ignore_call24 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter12_ignore_call24 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter13_ignore_call24 : BOOLEAN;
    signal ap_block_state15_pp0_stage0_iter14_ignore_call24 : BOOLEAN;
    signal ap_block_state16_pp0_stage0_iter15_ignore_call24 : BOOLEAN;
    signal ap_block_state17_pp0_stage0_iter16_ignore_call24 : BOOLEAN;
    signal ap_block_state18_pp0_stage0_iter17_ignore_call24 : BOOLEAN;
    signal ap_block_state19_pp0_stage0_iter18_ignore_call24 : BOOLEAN;
    signal ap_block_state20_pp0_stage0_iter19_ignore_call24 : BOOLEAN;
    signal ap_block_state21_pp0_stage0_iter20_ignore_call24 : BOOLEAN;
    signal ap_block_state22_pp0_stage0_iter21_ignore_call24 : BOOLEAN;
    signal ap_block_state23_pp0_stage0_iter22_ignore_call24 : BOOLEAN;
    signal ap_block_state24_pp0_stage0_iter23_ignore_call24 : BOOLEAN;
    signal ap_block_state25_pp0_stage0_iter24_ignore_call24 : BOOLEAN;
    signal ap_block_state26_pp0_stage0_iter25_ignore_call24 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp51 : BOOLEAN;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal trunc_ln1494_fu_75_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln703_17_fu_85_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_fu_106_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln3_fu_149_p4 : STD_LOGIC_VECTOR (18 downto 0);
    signal p_Val2_17_fu_135_p4 : STD_LOGIC_VECTOR (19 downto 0);
    signal rhs_V_fu_162_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal ret_V_1_fu_166_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal icmp_ln251_fu_182_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln251_fu_187_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln4_fu_172_p4 : STD_LOGIC_VECTOR (19 downto 0);
    signal zext_ln700_fu_158_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal icmp_ln879_1_fu_237_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln879_fu_257_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln879_fu_263_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_29_fu_252_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_27_fu_274_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln879_fu_284_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_9_fu_242_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_29_fu_298_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln879_2_fu_247_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln879_fu_268_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln879_2_fu_308_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln879_3_fu_315_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln703_fu_330_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_26_fu_335_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_8_fu_352_p0 : STD_LOGIC_VECTOR (25 downto 0);
    signal r_V_8_fu_352_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_358_p0 : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_fu_358_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_358_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal ap_ce_reg : STD_LOGIC;
    signal in_V_int_reg : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_return_0_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_1_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_358_p10 : STD_LOGIC_VECTOR (20 downto 0);
    signal r_V_8_fu_352_p10 : STD_LOGIC_VECTOR (42 downto 0);

    component cordic_circ_apfixed IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        z_V_read : IN STD_LOGIC_VECTOR (19 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (20 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (20 downto 0);
        ap_ce : IN STD_LOGIC );
    end component;


    component metalgo_mul_mul_2bkb IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (25 downto 0);
        din1 : IN STD_LOGIC_VECTOR (16 downto 0);
        dout : OUT STD_LOGIC_VECTOR (42 downto 0) );
    end component;


    component metalgo_mac_muladcud IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (19 downto 0);
        din1 : IN STD_LOGIC_VECTOR (3 downto 0);
        din2 : IN STD_LOGIC_VECTOR (20 downto 0);
        dout : OUT STD_LOGIC_VECTOR (20 downto 0) );
    end component;



begin
    grp_cordic_circ_apfixed_fu_70 : component cordic_circ_apfixed
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        z_V_read => z_V_reg_406,
        ap_return_0 => grp_cordic_circ_apfixed_fu_70_ap_return_0,
        ap_return_1 => grp_cordic_circ_apfixed_fu_70_ap_return_1,
        ap_ce => grp_cordic_circ_apfixed_fu_70_ap_ce);

    metalgo_mul_mul_2bkb_U4 : component metalgo_mul_mul_2bkb
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 26,
        din1_WIDTH => 17,
        dout_WIDTH => 43)
    port map (
        din0 => r_V_8_fu_352_p0,
        din1 => r_V_8_fu_352_p1,
        dout => r_V_8_fu_352_p2);

    metalgo_mac_muladcud_U5 : component metalgo_mac_muladcud
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 20,
        din1_WIDTH => 4,
        din2_WIDTH => 21,
        dout_WIDTH => 21)
    port map (
        din0 => grp_fu_358_p0,
        din1 => grp_fu_358_p1,
        din2 => grp_fu_358_p2,
        dout => grp_fu_358_p3);





    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_0_int_reg <= p_Val2_26_fu_335_p3;
                ap_return_1_int_reg <= select_ln879_4_reg_439;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                empty_reg_411 <= empty_fu_205_p1;
                icmp_ln879_reg_401 <= icmp_ln879_fu_144_p2;
                icmp_ln879_reg_401_pp0_iter10_reg <= icmp_ln879_reg_401_pp0_iter9_reg;
                icmp_ln879_reg_401_pp0_iter11_reg <= icmp_ln879_reg_401_pp0_iter10_reg;
                icmp_ln879_reg_401_pp0_iter12_reg <= icmp_ln879_reg_401_pp0_iter11_reg;
                icmp_ln879_reg_401_pp0_iter13_reg <= icmp_ln879_reg_401_pp0_iter12_reg;
                icmp_ln879_reg_401_pp0_iter14_reg <= icmp_ln879_reg_401_pp0_iter13_reg;
                icmp_ln879_reg_401_pp0_iter15_reg <= icmp_ln879_reg_401_pp0_iter14_reg;
                icmp_ln879_reg_401_pp0_iter16_reg <= icmp_ln879_reg_401_pp0_iter15_reg;
                icmp_ln879_reg_401_pp0_iter17_reg <= icmp_ln879_reg_401_pp0_iter16_reg;
                icmp_ln879_reg_401_pp0_iter18_reg <= icmp_ln879_reg_401_pp0_iter17_reg;
                icmp_ln879_reg_401_pp0_iter19_reg <= icmp_ln879_reg_401_pp0_iter18_reg;
                icmp_ln879_reg_401_pp0_iter20_reg <= icmp_ln879_reg_401_pp0_iter19_reg;
                icmp_ln879_reg_401_pp0_iter21_reg <= icmp_ln879_reg_401_pp0_iter20_reg;
                icmp_ln879_reg_401_pp0_iter22_reg <= icmp_ln879_reg_401_pp0_iter21_reg;
                icmp_ln879_reg_401_pp0_iter23_reg <= icmp_ln879_reg_401_pp0_iter22_reg;
                icmp_ln879_reg_401_pp0_iter4_reg <= icmp_ln879_reg_401;
                icmp_ln879_reg_401_pp0_iter5_reg <= icmp_ln879_reg_401_pp0_iter4_reg;
                icmp_ln879_reg_401_pp0_iter6_reg <= icmp_ln879_reg_401_pp0_iter5_reg;
                icmp_ln879_reg_401_pp0_iter7_reg <= icmp_ln879_reg_401_pp0_iter6_reg;
                icmp_ln879_reg_401_pp0_iter8_reg <= icmp_ln879_reg_401_pp0_iter7_reg;
                icmp_ln879_reg_401_pp0_iter9_reg <= icmp_ln879_reg_401_pp0_iter8_reg;
                k_V_reg_387 <= r_V_8_reg_381(40 downto 39);
                k_V_reg_387_pp0_iter10_reg <= k_V_reg_387_pp0_iter9_reg;
                k_V_reg_387_pp0_iter11_reg <= k_V_reg_387_pp0_iter10_reg;
                k_V_reg_387_pp0_iter12_reg <= k_V_reg_387_pp0_iter11_reg;
                k_V_reg_387_pp0_iter13_reg <= k_V_reg_387_pp0_iter12_reg;
                k_V_reg_387_pp0_iter14_reg <= k_V_reg_387_pp0_iter13_reg;
                k_V_reg_387_pp0_iter15_reg <= k_V_reg_387_pp0_iter14_reg;
                k_V_reg_387_pp0_iter16_reg <= k_V_reg_387_pp0_iter15_reg;
                k_V_reg_387_pp0_iter17_reg <= k_V_reg_387_pp0_iter16_reg;
                k_V_reg_387_pp0_iter18_reg <= k_V_reg_387_pp0_iter17_reg;
                k_V_reg_387_pp0_iter19_reg <= k_V_reg_387_pp0_iter18_reg;
                k_V_reg_387_pp0_iter20_reg <= k_V_reg_387_pp0_iter19_reg;
                k_V_reg_387_pp0_iter21_reg <= k_V_reg_387_pp0_iter20_reg;
                k_V_reg_387_pp0_iter22_reg <= k_V_reg_387_pp0_iter21_reg;
                k_V_reg_387_pp0_iter23_reg <= k_V_reg_387_pp0_iter22_reg;
                k_V_reg_387_pp0_iter3_reg <= k_V_reg_387;
                k_V_reg_387_pp0_iter4_reg <= k_V_reg_387_pp0_iter3_reg;
                k_V_reg_387_pp0_iter5_reg <= k_V_reg_387_pp0_iter4_reg;
                k_V_reg_387_pp0_iter6_reg <= k_V_reg_387_pp0_iter5_reg;
                k_V_reg_387_pp0_iter7_reg <= k_V_reg_387_pp0_iter6_reg;
                k_V_reg_387_pp0_iter8_reg <= k_V_reg_387_pp0_iter7_reg;
                k_V_reg_387_pp0_iter9_reg <= k_V_reg_387_pp0_iter8_reg;
                p_Val2_25_reg_433 <= p_Val2_25_fu_291_p3;
                p_Val2_s_reg_371 <= p_Val2_s_fu_91_p3;
                r_V_8_reg_381 <= r_V_8_fu_352_p2;
                ret_V_reg_395 <= grp_fu_358_p3;
                select_ln879_4_reg_439 <= select_ln879_4_fu_322_p3;
                sign0_V_reg_366 <= sign0_V_fu_79_p2;
                sign0_V_reg_366_pp0_iter10_reg <= sign0_V_reg_366_pp0_iter9_reg;
                sign0_V_reg_366_pp0_iter11_reg <= sign0_V_reg_366_pp0_iter10_reg;
                sign0_V_reg_366_pp0_iter12_reg <= sign0_V_reg_366_pp0_iter11_reg;
                sign0_V_reg_366_pp0_iter13_reg <= sign0_V_reg_366_pp0_iter12_reg;
                sign0_V_reg_366_pp0_iter14_reg <= sign0_V_reg_366_pp0_iter13_reg;
                sign0_V_reg_366_pp0_iter15_reg <= sign0_V_reg_366_pp0_iter14_reg;
                sign0_V_reg_366_pp0_iter16_reg <= sign0_V_reg_366_pp0_iter15_reg;
                sign0_V_reg_366_pp0_iter17_reg <= sign0_V_reg_366_pp0_iter16_reg;
                sign0_V_reg_366_pp0_iter18_reg <= sign0_V_reg_366_pp0_iter17_reg;
                sign0_V_reg_366_pp0_iter19_reg <= sign0_V_reg_366_pp0_iter18_reg;
                sign0_V_reg_366_pp0_iter1_reg <= sign0_V_reg_366;
                sign0_V_reg_366_pp0_iter20_reg <= sign0_V_reg_366_pp0_iter19_reg;
                sign0_V_reg_366_pp0_iter21_reg <= sign0_V_reg_366_pp0_iter20_reg;
                sign0_V_reg_366_pp0_iter22_reg <= sign0_V_reg_366_pp0_iter21_reg;
                sign0_V_reg_366_pp0_iter23_reg <= sign0_V_reg_366_pp0_iter22_reg;
                sign0_V_reg_366_pp0_iter24_reg <= sign0_V_reg_366_pp0_iter23_reg;
                sign0_V_reg_366_pp0_iter2_reg <= sign0_V_reg_366_pp0_iter1_reg;
                sign0_V_reg_366_pp0_iter3_reg <= sign0_V_reg_366_pp0_iter2_reg;
                sign0_V_reg_366_pp0_iter4_reg <= sign0_V_reg_366_pp0_iter3_reg;
                sign0_V_reg_366_pp0_iter5_reg <= sign0_V_reg_366_pp0_iter4_reg;
                sign0_V_reg_366_pp0_iter6_reg <= sign0_V_reg_366_pp0_iter5_reg;
                sign0_V_reg_366_pp0_iter7_reg <= sign0_V_reg_366_pp0_iter6_reg;
                sign0_V_reg_366_pp0_iter8_reg <= sign0_V_reg_366_pp0_iter7_reg;
                sign0_V_reg_366_pp0_iter9_reg <= sign0_V_reg_366_pp0_iter8_reg;
                tmp_28_reg_427 <= grp_cordic_circ_apfixed_fu_70_ap_return_0(19 downto 4);
                tmp_s_reg_421 <= grp_cordic_circ_apfixed_fu_70_ap_return_1(19 downto 4);
                trunc_ln266_reg_416 <= trunc_ln266_fu_213_p1;
                trunc_ln728_reg_376 <= trunc_ln728_fu_99_p1;
                trunc_ln728_reg_376_pp0_iter1_reg <= trunc_ln728_reg_376;
                z_V_reg_406 <= z_V_fu_193_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                in_V_int_reg <= in_V;
            end if;
        end if;
    end process;
    and_ln879_fu_263_p2 <= (xor_ln879_fu_257_p2 and icmp_ln879_reg_401_pp0_iter23_reg);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_ignoreCallOp51 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage0_iter9_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter11 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter11_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter12_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage0_iter13 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage0_iter13_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state15_pp0_stage0_iter14 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state15_pp0_stage0_iter14_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state16_pp0_stage0_iter15 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state16_pp0_stage0_iter15_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state17_pp0_stage0_iter16 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state17_pp0_stage0_iter16_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state18_pp0_stage0_iter17 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state18_pp0_stage0_iter17_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state19_pp0_stage0_iter18 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state19_pp0_stage0_iter18_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state20_pp0_stage0_iter19 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state20_pp0_stage0_iter19_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state21_pp0_stage0_iter20 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state21_pp0_stage0_iter20_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state22_pp0_stage0_iter21 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state22_pp0_stage0_iter21_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state23_pp0_stage0_iter22 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state23_pp0_stage0_iter22_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state24_pp0_stage0_iter23 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state24_pp0_stage0_iter23_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state25_pp0_stage0_iter24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state25_pp0_stage0_iter24_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state26_pp0_stage0_iter25 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state26_pp0_stage0_iter25_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_0_assign_proc : process(p_Val2_26_fu_335_p3, ap_ce_reg, ap_return_0_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_0 <= ap_return_0_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_0 <= p_Val2_26_fu_335_p3;
        end if; 
    end process;


    ap_return_1_assign_proc : process(select_ln879_4_reg_439, ap_ce_reg, ap_return_1_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_1 <= ap_return_1_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_1 <= select_ln879_4_reg_439;
        end if; 
    end process;

    empty_fu_205_p1 <= grp_cordic_circ_apfixed_fu_70_ap_return_0(20 - 1 downto 0);

    grp_cordic_circ_apfixed_fu_70_ap_ce_assign_proc : process(ap_block_pp0_stage0_11001_ignoreCallOp51, ap_ce_reg)
    begin
        if (((ap_const_logic_1 = ap_ce_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp51))) then 
            grp_cordic_circ_apfixed_fu_70_ap_ce <= ap_const_logic_1;
        else 
            grp_cordic_circ_apfixed_fu_70_ap_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_358_p0 <= ap_const_lv21_6DE05(20 - 1 downto 0);
    grp_fu_358_p1 <= grp_fu_358_p10(4 - 1 downto 0);
    grp_fu_358_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_106_p4),21));
    grp_fu_358_p2 <= (trunc_ln728_reg_376_pp0_iter1_reg & ap_const_lv6_0);
    icmp_ln251_fu_182_p2 <= "1" when (k_V_reg_387 = ap_const_lv2_3) else "0";
    icmp_ln879_1_fu_237_p2 <= "1" when (k_V_reg_387_pp0_iter23_reg = ap_const_lv2_0) else "0";
    icmp_ln879_2_fu_247_p2 <= "1" when (k_V_reg_387_pp0_iter23_reg = ap_const_lv2_2) else "0";
    icmp_ln879_fu_144_p2 <= "1" when (k_V_reg_387 = ap_const_lv2_1) else "0";
    or_ln251_fu_187_p2 <= (icmp_ln879_fu_144_p2 or icmp_ln251_fu_182_p2);
    or_ln879_fu_268_p2 <= (icmp_ln879_1_fu_237_p2 or and_ln879_fu_263_p2);
    p_Val2_17_fu_135_p4 <= ret_V_reg_395(20 downto 1);
    p_Val2_25_fu_291_p3 <= 
        tmp_s_reg_421 when (icmp_ln879_1_fu_237_p2(0) = '1') else 
        select_ln879_fu_284_p3;
    p_Val2_26_fu_335_p3 <= 
        p_Val2_25_reg_433 when (sign0_V_reg_366_pp0_iter24_reg(0) = '1') else 
        sub_ln703_fu_330_p2;
    p_Val2_29_fu_252_p2 <= std_logic_vector(unsigned(ap_const_lv20_0) - unsigned(trunc_ln266_reg_416));
    p_Val2_s_fu_91_p3 <= 
        trunc_ln1494_fu_75_p1 when (sign0_V_fu_79_p2(0) = '1') else 
        sub_ln703_17_fu_85_p2;
    r_V_8_fu_352_p0 <= ap_const_lv43_145F306(26 - 1 downto 0);
    r_V_8_fu_352_p1 <= r_V_8_fu_352_p10(17 - 1 downto 0);
    r_V_8_fu_352_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Val2_s_reg_371),43));
    r_V_9_fu_242_p2 <= std_logic_vector(unsigned(ap_const_lv20_0) - unsigned(empty_reg_411));
    ret_V_1_fu_166_p2 <= std_logic_vector(unsigned(ap_const_lv21_C90FD) - unsigned(rhs_V_fu_162_p1));
    rhs_V_fu_162_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Val2_17_fu_135_p4),21));
    select_ln879_2_fu_308_p3 <= 
        tmp_28_reg_427 when (icmp_ln879_1_fu_237_p2(0) = '1') else 
        tmp_29_fu_298_p4;
    select_ln879_3_fu_315_p3 <= 
        tmp_29_fu_298_p4 when (icmp_ln879_2_fu_247_p2(0) = '1') else 
        tmp_28_reg_427;
    select_ln879_4_fu_322_p3 <= 
        select_ln879_2_fu_308_p3 when (or_ln879_fu_268_p2(0) = '1') else 
        select_ln879_3_fu_315_p3;
    select_ln879_fu_284_p3 <= 
        tmp_s_reg_421 when (and_ln879_fu_263_p2(0) = '1') else 
        tmp_27_fu_274_p4;
    sign0_V_fu_79_p2 <= "1" when (signed(in_V_int_reg) > signed(ap_const_lv18_0)) else "0";
    sub_ln703_17_fu_85_p2 <= std_logic_vector(unsigned(ap_const_lv17_0) - unsigned(trunc_ln1494_fu_75_p1));
    sub_ln703_fu_330_p2 <= std_logic_vector(unsigned(ap_const_lv16_0) - unsigned(p_Val2_25_reg_433));
    tmp_27_fu_274_p4 <= p_Val2_29_fu_252_p2(19 downto 4);
    tmp_29_fu_298_p4 <= r_V_9_fu_242_p2(19 downto 4);
    tmp_fu_106_p4 <= r_V_8_reg_381(42 downto 39);
    trunc_ln1494_fu_75_p1 <= in_V_int_reg(17 - 1 downto 0);
    trunc_ln266_fu_213_p1 <= grp_cordic_circ_apfixed_fu_70_ap_return_1(20 - 1 downto 0);
    trunc_ln3_fu_149_p4 <= ret_V_reg_395(20 downto 2);
    trunc_ln4_fu_172_p4 <= ret_V_1_fu_166_p2(20 downto 1);
    trunc_ln728_fu_99_p1 <= p_Val2_s_fu_91_p3(15 - 1 downto 0);
    xor_ln879_fu_257_p2 <= (icmp_ln879_1_fu_237_p2 xor ap_const_lv1_1);
    z_V_fu_193_p3 <= 
        trunc_ln4_fu_172_p4 when (or_ln251_fu_187_p2(0) = '1') else 
        zext_ln700_fu_158_p1;
    zext_ln700_fu_158_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln3_fu_149_p4),20));
end behav;
